'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WeatherStationService.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date and Time, Temperature, Humidity, Pressure
        '''.
        '''</summary>
        Friend ReadOnly Property EmptyLog() As String
            Get
                Return ResourceManager.GetString("EmptyLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''  &lt;meta http-equiv=&quot;refresh&quot; content=&quot;10&quot;&gt;
        '''  &lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;content-type&quot;&gt;
        '''  &lt;title&gt;Backyard Weather Station&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''  Inital update overdue!
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property FirstUpdateOverdue() As String
            Get
                Return ResourceManager.GetString("FirstUpdateOverdue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        '''  &lt;meta http-equiv=&quot;refresh&quot; content=&quot;10&quot;&gt;
        '''  &lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;content-type&quot;&gt;
        '''  &lt;title&gt;Backyard Weather Station&lt;/title&gt;
        '''  &lt;style&gt;
        '''    html {
        '''     font-family: Arial;
        '''     display: inline-block;
        '''     margin: 0px auto;
        '''     text-align: center;
        '''    }
        '''    h2 { font-size: 3.0rem; }
        '''    p { font-size: 3.0rem; }
        '''    .units { font-size: 1.2rem; }
        '''    .x-l [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TemplateHTML() As String
            Get
                Return ResourceManager.GetString("TemplateHTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''  &lt;meta http-equiv=&quot;refresh&quot; content=&quot;10&quot;&gt;
        '''  &lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;content-type&quot;&gt;
        '''  &lt;title&gt;Backyard Weather Station&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''  Update coming soon!
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property UpdateComingSoonHTML() As String
            Get
                Return ResourceManager.GetString("UpdateComingSoonHTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property weather() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("weather", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
